name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: mouli.muralikrishnan@straive.com
        run: echo "Hello, world! This action was triggered by a $(echo $GITHUB_EVENT_NAME) event on branch $(echo $GITHUB_REF)"

      - name: Another Step (Optional)
        run: |
          echo "This is another step."
          echo "You can run multiple commands here."

  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make a change and commit
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt
          git config --local user.email "mouli.muralikrishnan@straive.com"
          git config --local user.name "GitHub Action"
          git add daily_commit.txt
          git commit -m "Daily commit on $(date)"
